### ISSUE TITLE
takeinPaymentとtakeoutPaymentの違いって何ですか？

### ISSUE THREAD

**Issue by hokosugi** [ICME-Lab/ICP#1]
ledger.moのtakeinPaymentはウォレットの残金を手数料分を差っ引いた額全てを出金しているように見えますが、takeoutPaymentは具体的にどういうシチュエーションで利用することを想定していますか。第２引数の `amountE8s` は、何のための金額か分かっていないです。

**Comment by ClankPan** [comment]
Thank you for your question.
I understand Japanese, but could you please write it in English for others in the future?

**Comment by hokosugi** [comment]
It appears that ledger.mo's function`takeinPayment` withdraws the entire amount remaining in the wallet, minus fees, but what specific situation is function `takeoutPayment` intended to be used for? I don't know what the second argument, `amountE8s` is for.

**Comment by ClankPan** [comment]
`takeinPayment` moves ICP to canister's subaccount to mainaccount.
`takeoutPayment` transfers ICP from canister's mainaccount to another account.

**Comment by ClankPan** [comment]
`takeinPayment` moves ICP to canister's subaccount to mainaccount.
`takeoutPayment` transfers ICP from canister's mainaccount to another account.

**Comment by hokosugi** [comment]
I completely understand. 
I think it will be very useful.
Thank you.
